apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-helm
  labels:
    deployMethod: helm-with-pipeline
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd
    repoURL: https://github.com/nadeemshahzad/testing-helm.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
